### ISSUE TITLE
Dockerfile for helping devs

### ISSUE THREAD

**Issue by flaviostutz** [tsenart/vegeta#525] opened 2020-07-01 20:03 UTC
Provide a Dockerfile support to enable new incomers devs to develop without having to prepare his/hers local machine, causing incompatibilities with other dev's projects.

#### Proposal

Provide a Dockerfile and a docker-compose.yml file with an example on how to build/run Vegeta so that the specific tooling versions are very well defined.

#### Background

I am working on a new feature and decided to use successfuly Dockerfile in order to avoid having to prepare my host machine with libs/tools needed for building Vegeta.

#### Workarounds

Devs have to prepare his/hers machine with specific Make and Golang tools which may be incompatible with other projects the developer is working on too.

**Comment by Jmainguy** [comment] 2020-10-23 14:40
PR for this appears to be open at https://github.com/tsenart/vegeta/pull/534

**Comment by tsenart** [comment] 2023-08-09 13:18
Duplicate of #316

**Closed by tsenart** 2023-08-09 13:18 UTC
