### ISSUE TITLE
"Extra data in buffer" when trying to generate report

### ISSUE THREAD

**Issue by BenjiZombie** [tsenart/vegeta#204] opened 2016-10-21 18:32 UTC
Hi,

1. What version of the project are you using?
v6.1.1

2. What operating system and processor architecture are you using?
Windows 10 (I know, I know), x64
go version go1.7.3 windows/amd64

3. What did you do?
```
PS C:\Temp> echo "GET https://localhost/" | ./vegeta attack -insecure -duration=120s -workers=200 > results.bin

PS C:\Temp> cat .\results.bin | ./vegeta.exe report
```
4. What did you expect to see?
Textual report

5. What did you see instead?
`extra data in buffer`

It seems I can't generate any report (tried plot and the others as well) under Windows. `results.bin` file is 1MB in size.

Have you had any success under Windows?

Thanks

**Comment by tsenart** [comment] 2016-10-25 19:23
Can you attach your results.bin in here for me to debug?

**Comment by BenjiZombie** [comment] 2016-10-25 19:42
[results.zip](https://github.com/tsenart/vegeta/files/551618/results.zip)

Thanks

**Comment by tsenart** [comment] 2016-10-25 20:42
If you attempt a shorter attack and let it finish `-duration=5s`, does this still happen?

**Comment by BenjiZombie** [comment] 2016-10-26 13:52
Unfortunately, yes:

```
PS C:\Temp> echo "GET https://www.google.com/" | ./vegeta attack -insecure -duration=5s | tee results2.bin | ./vegeta report
2016/10/26 09:51:10 extra data in buffer
```

[results2.zip](https://github.com/tsenart/vegeta/files/553388/results2.zip)

**Comment by tsenart** [comment] 2016-10-26 14:10
I'm setting up a Windows VM to try to reproduce this.

**Comment by tsenart** [comment] 2016-10-26 15:08
Man, I can't even run a command on a Windows prompt. :-( 

Are you on normal command prompt, Powershell or BASH with the latest Linux compatibility mode?

**Comment by BenjiZombie** [comment] 2016-10-26 15:45
Using PowerShell

**Comment by tsenart** [comment] 2016-10-26 23:09
OK, the problem seems to be in the stdout / stdin in Powershell. Things seem to get corrupted with pipes and stdout redirection. Try this instead:

```
echo "GET https://www.google.com/" | ./vegeta attack -insecure -duration=2s -output="results.bin"
vegeta report -inputs="results.bin"
```

**Comment by tsenart** [comment] 2016-10-26 23:12
And this explains the why: https://brianreiter.org/2010/01/29/powershells-object-pipeline-corrupts-piped-binary-data/

This isn't a Vegeta problem, so closing this issue. Thanks for the report.

**Closed by tsenart** 2016-10-26 23:12 UTC
