### ISSUE TITLE
When http response header Content-Length: -1,  io.Copy cause error:Expected EOF

### ISSUE THREAD

**Issue by wangming1993** [tsenart/vegeta#166] opened 2016-01-07 06:40 UTC
When I had a attack with  reponse header: 
```
Content-Type: -1
```
Will cause error: ***Expected EOF***
 in: **lib/attack.go**   function **hit**  io.Copy,   line **235**

**Comment by tsenart** [comment] 2016-01-07 14:47
Contributions welcome!

**Comment by tsenart** [comment] 2016-04-03 19:26
Can't reproduce. If you can provide a reproducible test case, please do! Closing for now.

**Closed by tsenart** 2016-04-03 19:26 UTC
