### ISSUE TITLE
Support for response headers in dumper csv 

### ISSUE THREAD

**Issue by gchiesa** [tsenart/vegeta#320] opened 2018-07-24 14:49 UTC
#### Proposal
It would be useful to have in the csv dumper also the http response headers together with the other values already present

#### Background
During our test we track the request id via a response header so each specific request can be further analysed with detailed logs in the http server / application

#### Workarounds
There is no workaround at the moment.

**Comment by tsenart** [comment] 2018-07-24 19:21
Duplicate of https://github.com/tsenart/vegeta/issues/303

**Closed by tsenart** 2018-07-24 19:21 UTC
